### ISSUE TITLE
AssertionError with unsupervised.py

### ISSUE THREAD

**Issue by deakkon** [facebookresearch/MUSE#1]
Hi all,

not sure if this is an error on my end or not, but as I couldn't debug it myself I thought I would post it here. Same happens with both py2 and py3. 

Using:
numpy (1.13.3)
torch (0.3.0.post4)
torchvision (0.2.0)

No Faiss installed. 

When I run:

$CUDA_VISIBLE_DEVICES=2,3 /home/sevajuri/anaconda3/envs/torch3/bin/python unsupervised.py --src_lang en --tgt_lang fr  --src_emb wiki.en.vec --tgt_emb wiki.fr.vec --max_vocab=1000000

I get (after the first epoch):

Traceback (most recent call last):
  File "unsupervised.py", line 135, in <module>
    evaluator.all_eval(to_log)
  File "/home/sevajuri/projects/clef17/MUSE/src/evaluation/evaluator.py", line 190, in all_eval
    self.word_translation(to_log)
  File "/home/sevajuri/projects/clef17/MUSE/src/evaluation/evaluator.py", line 94, in word_translation
    method=method
  File "/home/sevajuri/projects/clef17/MUSE/src/evaluation/word_translation.py", line 88, in get_word_translation_accuracy
    dico = load_dictionary(path, word2id1, word2id2)
  File "/home/sevajuri/projects/clef17/MUSE/src/evaluation/word_translation.py", line 48, in load_dictionary
    assert os.path.isfile(path)
AssertionError

**Comment by glample** [comment]
Hi. It looks like the dictionary you are trying to load is not found. Did you run `./get_evaluation.sh` in the `data/` folder?

**Comment by deakkon** [comment]
Hi,

That must be it. I skipped that part as I had my own embedding I wanted to use and assumed, wrongly, I can skip that step.

Thank you for the clarification.

Best,
J.
