### ISSUE TITLE
error when running supervised.py

### ISSUE THREAD

**Issue by shihs** [facebookresearch/MUSE#157]
I tried to run the command from README

```
python supervised.py --src_lang en --tgt_lang es --src_emb data/wiki.en.vec --tgt_emb data/wiki.es.vec --n_refinement 5 --dico_train default
```

But I get the error below...
```
Traceback (most recent call last):
  File "supervised.py", line 78, in <module>
    trainer.load_training_dico(params.dico_train)
  File "xxx/Desktop/MUSE-master/src/trainer.py", line 150, in load_training_dico
    word2id1, word2id2
  File "xxx/Desktop/MUSE-master/src/evaluation/word_translation.py", line 49, in load_dictionary
    assert os.path.isfile(path)
AssertionError
```
I found the problem is the 'path', is line 149 in trainer.py
```
os.path.join(DIC_EVAL_PATH, filename)
```

So I printed it, the path is **xxx/../data/crosslingual/dictionaries/en-es.0-5000.txt**

I am not sure when does the directory 'crosslingual' and 'dictionaries' are made? 
How do I fix this problem? I don't think I should make them manually....

**Comment by YovaKem** [comment]
You have to run data/get_evaluation.sh to download the dictionaries.

**Comment by shr0815** [comment]
i have solved this by creating a new folder "crosslingual" in the directory "data":

XXX\XXX\XXX\data\crosslingual\dictionaries\XXX
