### ISSUE TITLE
PyTorch 0.4.0 compatibility - Problem running supervised experiment with EN-ZH language pairs

### ISSUE THREAD

**Issue by xiamx** [facebookresearch/MUSE#46]
#### Steps to reproduce
1. obtained evaluation dataset with the bash script.
2. obtained wiki.zh.vec and wiki.en.vec pretrained from fasttext.
```
python supervised.py --src_lang zh --tgt_lang en --src_emb /Tmp/xiamengx/cc18-st1-data/fasttext-embeddings/wiki.zh.vec --tgt_emb /Tmp/xiamengx/cc18-st1-data/fasttext-embeddings/wiki.en.vec --n_refinement 5
```

#### Expected
Training finishes successfully
#### Actual
TypeError is thrown

#### Logs
```
INFO - 04/26/18 08:42:05 - 0:00:00 - ============ Initialized logger ============
INFO - 04/26/18 08:42:05 - 0:00:00 - cuda: True
                                     dico_build: S2T&T2S
                                     dico_eval: default
                                     dico_max_rank: 10000
                                     dico_max_size: 0
                                     dico_method: csls_knn_10
                                     dico_min_size: 0
                                     dico_threshold: 0
                                     dico_train: default
                                     emb_dim: 300
                                     exp_id: 
                                     exp_name: debug
                                     exp_path: /u/xiamengx/src/nlpcc/MUSE/dumped/debug/ufwt0sef93
                                     export: txt
                                     max_vocab: 200000
                                     n_refinement: 5
                                     normalize_embeddings: 
                                     seed: -1
                                     src_emb: /Tmp/xiamengx/cc18-st1-data/fasttext-embeddings/wiki.zh.vec
                                     src_lang: zh
                                     tgt_emb: /Tmp/xiamengx/cc18-st1-data/fasttext-embeddings/wiki.en.vec
                                     tgt_lang: en
                                     verbose: 2
INFO - 04/26/18 08:42:05 - 0:00:00 - The experiment will be stored in /u/xiamengx/src/nlpcc/MUSE/dumped/debug/ufwt0sef93
INFO - 04/26/18 08:42:24 - 0:00:18 - Loaded 200000 pre-trained word embeddings.
INFO - 04/26/18 08:42:48 - 0:00:43 - Loaded 200000 pre-trained word embeddings.
INFO - 04/26/18 08:42:53 - 0:00:48 - Found 8891 pairs of words in the dictionary (5000 unique). 0 other pairs contained at least one unknown word (0 in lang1, 0 in lang2)
INFO - 04/26/18 08:42:54 - 0:00:48 - Starting iteration 0...
INFO - 04/26/18 08:42:54 - 0:00:48 - ====================================================================
INFO - 04/26/18 08:42:54 - 0:00:48 -                        Dataset      Found     Not found          Rho
INFO - 04/26/18 08:42:54 - 0:00:48 - ====================================================================
INFO - 04/26/18 08:42:54 - 0:00:48 -                  EN_WS-353-REL        252             0       0.6820
INFO - 04/26/18 08:42:54 - 0:00:48 -                    EN_VERB-143        144             0       0.3973
INFO - 04/26/18 08:42:54 - 0:00:49 -                   EN_MEN-TR-3k       3000             0       0.7637
INFO - 04/26/18 08:42:54 - 0:00:49 -                  EN_WS-353-SIM        203             0       0.7811
INFO - 04/26/18 08:42:54 - 0:00:49 -                   EN_SEMEVAL17        379             9       0.7216
INFO - 04/26/18 08:42:54 - 0:00:49 -                  EN_SIMLEX-999        998             1       0.3823
INFO - 04/26/18 08:42:54 - 0:00:49 -                      EN_YP-130        130             0       0.5333
INFO - 04/26/18 08:42:54 - 0:00:49 -                  EN_WS-353-ALL        353             0       0.7388
INFO - 04/26/18 08:42:54 - 0:00:49 -                       EN_MC-30         30             0       0.8123
INFO - 04/26/18 08:42:54 - 0:00:49 -                   EN_MTurk-287        286             1       0.6773
INFO - 04/26/18 08:42:54 - 0:00:49 -                   EN_MTurk-771        771             0       0.6689
INFO - 04/26/18 08:42:54 - 0:00:49 -                       EN_RG-65         65             0       0.7974
INFO - 04/26/18 08:42:54 - 0:00:49 -                 EN_RW-STANFORD       1323           711       0.5080
INFO - 04/26/18 08:42:54 - 0:00:49 - ====================================================================
INFO - 04/26/18 08:42:54 - 0:00:49 - Monolingual target word similarity score average: 0.65108
INFO - 04/26/18 08:42:54 - 0:00:49 - Found 2483 pairs of words in the dictionary (1500 unique). 0 other pairs contained at least one unknown word (0 in lang1, 0 in lang2)
INFO - 04/26/18 08:42:55 - 0:00:49 - 2483 source words - nn - Precision at k = 1: 5.598067
INFO - 04/26/18 08:42:55 - 0:00:50 - 2483 source words - nn - Precision at k = 5: 15.304068
INFO - 04/26/18 08:42:55 - 0:00:50 - 2483 source words - nn - Precision at k = 10: 21.546516
INFO - 04/26/18 08:42:55 - 0:00:50 - Found 2483 pairs of words in the dictionary (1500 unique). 0 other pairs contained at least one unknown word (0 in lang1, 0 in lang2)
INFO - 04/26/18 08:43:08 - 0:01:02 - 2483 source words - csls_knn_10 - Precision at k = 1: 15.183246
INFO - 04/26/18 08:43:08 - 0:01:02 - 2483 source words - csls_knn_10 - Precision at k = 5: 34.071687
INFO - 04/26/18 08:43:08 - 0:01:03 - 2483 source words - csls_knn_10 - Precision at k = 10: 42.690294
INFO - 04/26/18 08:43:15 - 0:01:09 - Building the train dictionary ...
INFO - 04/26/18 08:43:15 - 0:01:09 - New train dictionary of 6665 pairs.
INFO - 04/26/18 08:43:15 - 0:01:09 - Mean cosine (nn method, S2T build, 10000 max size): 0.60218
INFO - 04/26/18 08:43:48 - 0:01:42 - Building the train dictionary ...
INFO - 04/26/18 08:43:48 - 0:01:42 - New train dictionary of 5529 pairs.
INFO - 04/26/18 08:43:48 - 0:01:42 - Mean cosine (csls_knn_10 method, S2T build, 10000 max size): 0.59617
Traceback (most recent call last):
  File "supervised.py", line 101, in <module>
    logger.info("__log__:%s" % json.dumps(to_log))
  File "/u/xiamengx/anaconda3/envs/nlpcc/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/u/xiamengx/anaconda3/envs/nlpcc/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/u/xiamengx/anaconda3/envs/nlpcc/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/u/xiamengx/anaconda3/envs/nlpcc/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: tensor(0.6022, device='cuda:0') is not JSON serializable
```

#### Environment
```
Python 3.5.5 :: Anaconda, Inc
>>> torch.__version__
'0.4.0'
MUSE commit: a620cc8aa394d4eb345ecdeda5067b0b1ef30a6a
```

**Comment by xiamx** [comment]
I suspect that it's because I'm running on a newer version of pytorch, will try again with 0.3.1

**Comment by xiamx** [comment]
Yup working fine with 0.3.1. Can we add a note on the readme to hint that pytorch needs to be 0.3.1 instead of 0.4.0 ?

**Comment by xiamx** [comment]
Thanks for the prompt response @glample  😃

**Comment by glample** [comment]
Fixed in https://github.com/facebookresearch/MUSE/commit/3d1fbdea6f85ce25483851a731c69e192125e3bb and https://github.com/facebookresearch/MUSE/commit/c96829fb2f0a26d6dfb45a5a097e08260bba862c.
