### ISSUE TITLE
Issue loading gensim trained word embeddings

### ISSUE THREAD

**Issue by duttahritwik** [facebookresearch/MUSE#62]
Hi,
I am using word embeddings generated by **gensim library** on a dataset of mine.
I have embeddings in two different languages, English and Hindi.
I am using the code in the Load Embeddings section from demo.ipynb and I have run into a problem.
My complier states the error as:

****C:\Users\DuttaHritwik\Anaconda3\lib\site-packages\gensim\utils.py:860: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
Traceback (most recent call last):

  File "<ipython-input-1-6373803fa41f>", line 1, in <module>
    runfile('C:/Users/DuttaHritwik/Desktop/First Research Paper/Data/MUSE_Eng_Hin.py', wdir='C:/Users/DuttaHritwik/Desktop/First Research Paper/Data')

  File "C:\Users\DuttaHritwik\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "C:\Users\DuttaHritwik\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/DuttaHritwik/Desktop/First Research Paper/Data/MUSE_Eng_Hin.py", line 45, in <module>
    src_embeddings,src_id2word,src_word2id=load_vec(src_path, nmax)

  File "C:/Users/DuttaHritwik/Desktop/First Research Paper/Data/MUSE_Eng_Hin.py", line 37, in load_vec
    embeddings=np.vstack(vectors)

  File "C:\Users\DuttaHritwik\Anaconda3\lib\site-packages\numpy\core\shape_base.py", line 234, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly****

I don't know if there is an issue with the format of the file containing the word embeddings, but I tried and made sure that the format is a word, followed by it's word vector in the same line.
I used the embeddings provided here and they seemed to work fine. In case you're wondering, the word vectors are 300 dimensional numpy arrays.

I have also attached the text files for your reference.
P.S. Since this is only a trial, I have just used 10 word vectors.
I would be grateful if my problem is solved.
Thanks!
[English_vectors.txt](https://github.com/facebookresearch/MUSE/files/2195352/English_vectors.txt)
[Hindi_vectors.txt](https://github.com/facebookresearch/MUSE/files/2195353/Hindi_vectors.txt)

**Comment by aconneau** [comment]
Your text file has a different format than the one we used. There are brackets "[" and "]" in the lines. That might explain the error?

**Comment by aconneau** [comment]
On that line: embeddings=np.vstack(vectors) 
your error says that there is one element of the array "vectors" that is not of size 300 basically. You could try to open the debugger there ("import pdb; pdb.set_trace()") in that to see what happened?
