### ISSUE TITLE
RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

### ISSUE THREAD

**Issue by xpqr** [facebookresearch/MUSE#85]
with the command:
**python unsupervised.py --src_lang hi --tgt_lang en --src_emb 500_hi.vec --tgt_emb 500_en.vec --n_refinement 5**
INFO - 10/29/18 13:04:41 - 0:00:00 - Loaded 499 pre-trained word embeddings.
INFO - 10/29/18 13:04:45 - 0:00:04 - Loaded 470 pre-trained word embeddings.
INFO - 10/29/18 13:04:45 - 0:00:04 - ----> ADVERSARIAL TRAINING <----
                                  
INFO - 10/29/18 13:04:45 - 0:00:04 - Starting adversarial training epoch 0...
Traceback (most recent call last):
  File "unsupervised.py", line 118, in <module>
    trainer.dis_step(stats)
  File "/home1/xyz/MUSE/src/trainer.py", line 90, in dis_step
    x, y = self.get_dis_xy(volatile=True)
  File "/home1/xyz/MUSE/src/trainer.py", line 61, in get_dis_xy
    assert mf <= min(len(self.src_dico), len(self.tgt_dico))
AssertionError
...................................................................................................................................................................
with the command:
**python unsupervised.py --src_lang hi --tgt_lang en --src_emb 500_hi.vec --tgt_emb 500_en.vec --n_refinement 5 --dis_most_frequent 0**

INFO - 10/29/18 12:59:01 - 0:18:54 - 988000 - Discriminator loss: 0.6913 - 1771 samples/s
INFO - 10/29/18 12:59:05 - 0:18:58 - 992000 - Discriminator loss: 0.6916 - 1809 samples/s
INFO - 10/29/18 12:59:09 - 0:19:03 - 996000 - Discriminator loss: 0.6916 - 1789 samples/s
INFO - 10/29/18 12:59:14 - 0:19:07 - Found 6 pairs of words in the dictionary (6 unique). 1957 other pairs contained at least one unknown word (1951 in lang1, 1926 in lang2)
INFO - 10/29/18 12:59:14 - 0:19:07 - 6 source words - nn - Precision at k = 1: 0.000000
INFO - 10/29/18 12:59:14 - 0:19:07 - 6 source words - nn - Precision at k = 5: 0.000000
INFO - 10/29/18 12:59:14 - 0:19:07 - 6 source words - nn - Precision at k = 10: 0.000000
INFO - 10/29/18 12:59:14 - 0:19:07 - Found 6 pairs of words in the dictionary (6 unique). 1957 other pairs contained at least one unknown word (1951 in lang1, 1926 in lang2)
INFO - 10/29/18 12:59:15 - 0:19:08 - 6 source words - csls_knn_10 - Precision at k = 1: 0.000000
INFO - 10/29/18 12:59:15 - 0:19:08 - 6 source words - csls_knn_10 - Precision at k = 5: 0.000000
INFO - 10/29/18 12:59:15 - 0:19:08 - 6 source words - csls_knn_10 - Precision at k = 10: 0.000000
Traceback (most recent call last):
  File "unsupervised.py", line 139, in <module>
    evaluator.all_eval(to_log)
  File "/home1/xyz/MUSE/src/evaluation/evaluator.py", line 219, in all_eval
    self.dist_mean_cosine(to_log)
  File "/home1/xyz/MUSE/src/evaluation/evaluator.py", line 198, in dist_mean_cosine
    s2t_candidates = get_candidates(src_emb, tgt_emb, _params)
  File "/home1/xyz/MUSE/src/dico_builder.py", line 38, in get_candidates
    scores = emb2.mm(emb1[i:min(n_src, i + bs)].transpose(0, 1)).transpose(0, 1)
**RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)**

**Comment by glample** [comment]
Hi,

Can you look whether this pull request fixed the problem for you? https://github.com/facebookresearch/MUSE/pull/84

**Comment by kamalg92** [comment]
Resolved. Thanks
