### ISSUE TITLE
KeyError: 'precision_at_1-csls_knn_10'

### ISSUE THREAD

**Issue by SnowyCate** [facebookresearch/MUSE#98]
I don't seem to understand this error. This happened during training (supervised). Can someone help me understand what's the cause of it? I would really appreciate your help, thank you! 

- Traceback (most recent call last):
  File "supervised.py", line 105, in <module>
    trainer.save_best(to_log, VALIDATION_METRIC)
  File "C:\Users\ZENON\Desktop\new\MUSE-master\src\trainer.py", line 220, in save_best
    if to_log[metric] > self.best_valid_metric:
KeyError: 'precision_at_1-csls_knn_10'

Parameters:
- cuda: True
   dico_build: S2T&T2S
   dico_eval: default
   dico_max_rank: 10000
   dico_max_size: 0
   dico_method: csls_knn_10
   dico_min_size: 0
   dico_threshold: 0
   dico_train: default
   emb_dim: 300
   exp_id:
   exp_name: debug
    exp_path: C:\Users\ZENON\Desktop\new\MUSE-master\dumped\debug\ey7xloc5wt
   export: txt
   max_vocab: 200000
   n_refinement: 5
   normalize_embeddings:
   seed: -1
   src_emb: data/wiki.en.vec
   src_lang: en
   tgt_emb: data/wiki.tl.vec
   tgt_lang: tl
   verbose: 2

**Comment by jlabhishek** [comment]
this did not occur with --cuda False , can someone explain?

**Comment by sanjanasri** [comment]
Hi,

I got the same  error after some two iterations even kept --cuda False. Any suggestions would be helpful
